[package]
name = "kelp"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { version = "2.0.3", default-features = false }
goblin = { version = "0.9.2", default-features = false, features = ["elf64", "elf32"] }