[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
rustflags = ["-Cforce-frame-pointers=true", "-Cdebuginfo=2"]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]