[package]
name = "novos"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["kernel"]

[build-dependencies]
kernel = {path = "kernel", artifact = "bin", target = "x86_64-unknown-none"}

[dependencies]
lazy_static = "1.5.0"
regex = "1.10.6"

