[package]
name = "kvmm"
version = "0.1.0"
edition = "2024"

[dependencies]
arrayvec = {version = "0.7.6", default-features = false}
log = "0.4.27"
spin = "0.10.0"
x86_64 = "0.15.2"

[features]
default = []
alloc = []
