[package]
name = "kvmm"
version = "0.1.0"
edition = "2024"

[dependencies]
arrayvec = {version = "0.7.6", default-features = false}
cake = { path = "../cake" }
x86_64 = "0.15.2"
bitvec = { version = "1.0.1", default-features = false, features = ["atomic"] }

[features]
default = []
alloc = []
