[package]
name = "kalloc"
version = "0.1.0"
edition = "2024"

[dependencies]
cake = { path = "../cake" }

[profile.test]
debug = true

# This is so that `rust-analyzer` doesn't crash and burn
[target.'cfg(unix)'.dev-dependencies]
ctor = "0.4.1"
env_logger = "0.11.7"

[lints]
workspace = true