[package]
name = "kserial"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { version = "2.0.7", default-features = false }
spin = "0.9.8"

[features]
default = []
std = []
client = []
server = ["std"]
