[package]
name = "pcibin"
version = "0.1.0"
edition = "2024"

[features]
default = ["generate"]
parse = ["no_std"]
no_std = []
generate = ["dep:ureq"]

[dependencies]
ureq = {version = "3.0.4", optional = true}

